from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class SignalInfo:
    """Structured, immutable snapshot of the signal generated by the quantitative engine."""

    action: str  # "BUY", "SELL", "WAIT"
    direction: str  # "LONG", "SHORT", "NEUTRAL"
    confidence: float  # 0.0 to 1.0
    reasoning: str = ""
    positives: tuple[str, ...] = field(default_factory=tuple)
    warnings: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dictionary."""
        d = asdict(self)
        d["positives"] = list(self.positives)
        d["warnings"] = list(self.warnings)
        return d


@dataclass(frozen=True)
class RiskMetrics:
    """Structured, immutable snapshot of the risk parameters evaluated by the quantitative engine."""

    stop_loss: float | None = None
    take_profit: float | None = None
    risk_ratio: float | None = None
    risk_category: str = ""
    atr: float | None = None
    tp_multiplier: float | None = None
    sl_multiplier: float | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class MarketContext:
    """Consolidated, immutable context container consumed by the AI interpretation layer.

    Contains exclusively existing quantitative outputs from closed candle T.
    Does NOT calculate or mutate any indicator, prediction, signal, or risk value.
    """

    timestamp: pd.Timestamp
    symbol: str
    timeframe: str
    current_price: float
    market_regime: str
    predictive_score: float
    quant_score: float
    signal: SignalInfo
    risk: RiskMetrics
    technical_indicators: dict[str, Any] = field(default_factory=dict)
    volume_profile: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dictionary."""
        return {
            "timestamp": str(self.timestamp),
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "current_price": self.current_price,
            "market_regime": self.market_regime,
            "predictive_score": self.predictive_score,
            "quant_score": self.quant_score,
            "signal": self.signal.to_dict(),
            "risk": self.risk.to_dict(),
            "technical_indicators": dict(self.technical_indicators),
            "volume_profile": dict(self.volume_profile),
            "metadata": dict(self.metadata),
        }

    def format_for_prompt(self) -> str:
        """Format the quantitative context into clean, structured Markdown for LLM prompt ingestion."""
        lines = [
            f"# Market Context: {self.symbol} ({self.timeframe})",
            f"- Timestamp (Closed Candle T): {self.timestamp}",
            f"- Current Price: {self.current_price:,.2f}",
            "",
            "## Quantitative Assessment",
            f"- Quant Score: {self.quant_score:.1f}/100",
            f"- Predictive Score: {self.predictive_score:.2f} (Scale: 0.0 - 1.0)",
            f"- Market Regime: {self.market_regime}",
            "",
            "## Signal",
            f"- Action: {self.signal.action}",
            f"- Direction: {self.signal.direction}",
            f"- Confidence: {self.signal.confidence * 100:.1f}%",
            f"- Primary Reasoning: {self.signal.reasoning or 'N/A'}",
        ]

        if self.signal.positives:
            lines.append("- Supporting Factors:")
            for p in self.signal.positives:
                lines.append(f"  + {p}")

        if self.signal.warnings:
            lines.append("- Risk Warnings:")
            for w in self.signal.warnings:
                lines.append(f"  - {w}")

        lines.extend([
            "",
            "## Risk & Execution Boundaries",
            f"- Risk Category: {self.risk.risk_category or 'N/A'}",
            f"- Stop Loss: {f'{self.risk.stop_loss:,.2f}' if self.risk.stop_loss is not None else 'None'}",
            f"- Take Profit: {f'{self.risk.take_profit:,.2f}' if self.risk.take_profit is not None else 'None'}",
            f"- Risk/Reward Ratio: {f'{self.risk.risk_ratio:.2f}' if self.risk.risk_ratio is not None else 'N/A'}",
            f"- ATR: {f'{self.risk.atr:.2f}' if self.risk.atr is not None else 'N/A'}",
        ])

        if self.volume_profile:
            lines.extend([
                "",
                "## Volume Profile (Value Area)",
                f"- POC (Point of Control): {self.volume_profile.get('poc', 'N/A')}",
                f"- VAH (Value Area High): {self.volume_profile.get('vah', 'N/A')}",
                f"- VAL (Value Area Low): {self.volume_profile.get('val', 'N/A')}",
            ])

        if self.technical_indicators:
            lines.extend([
                "",
                "## Technical Indicators Snapshot",
            ])
            for k, v in sorted(self.technical_indicators.items()):
                if isinstance(v, float):
                    lines.append(f"- {k}: {v:.2f}")
                else:
                    lines.append(f"- {k}: {v}")

        return "\n".join(lines)


@dataclass(frozen=True)
class AgentExplanation:
    """Structured, immutable explanation produced by an AI Provider for human interpretation."""

    summary: str
    rationale: str
    key_drivers: tuple[str, ...] = field(default_factory=tuple)
    risk_assessment: str = ""
    confidence: float = 1.0
    raw_response: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dictionary."""
        d = asdict(self)
        d["key_drivers"] = list(self.key_drivers)
        return d


@dataclass(frozen=True)
class AgentMarketSummary:
    """Structured, immutable high-level market summary for dashboards and briefings."""

    title: str
    overview: str
    regime_interpretation: str
    outlook: str
    key_levels: dict[str, float] = field(default_factory=dict)
    raw_response: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dictionary."""
        return asdict(self)
