from __future__ import annotations

from unittest.mock import MagicMock, patch

import pandas as pd

from src.backtest_models import BacktestConfig
from src.backtest_runner import BacktestRunner
from src.notifications.channels.discord import DiscordWebhookChannel
from src.notifications.channels.telegram import TelegramChannel
from src.notifications.dispatcher import NotificationDispatcher
from src.streaming.candle_aggregator import CandleAggregator, KlineEvent
from src.streaming.live_engine import LiveExecutionEngine
from src.streaming.websocket_client import BinanceWebSocketClient


def test_live_replay_parity_against_backtest_runner(make_synthetic_candles):
    """CRITICAL PARITY TEST: Live Replay Mode vs Backtest Mode.

    Proves that for the exact same historical candle stream:
    BacktestRunner.run_backtest(...)
             vs
    LiveExecutionEngine attached to CandleAggregator

    produce identical:
    - timestamps
    - close prices
    - decisions / actions (BUY / SELL / WAIT)
    - trade directions (LONG / SHORT / NEUTRAL)
    - confidence scores
    - quant scores
    """
    # 1. Generate 225 deterministic synthetic candles
    candles = make_synthetic_candles(start="2025-01-01", periods=225, freq="1h", base_price=50000.0)

    # 2. Run Backtest Mode
    cfg = BacktestConfig(initial_capital=10_000.0)
    runner = BacktestRunner(config=cfg, predictive_mode=True)
    report = runner.run_backtest(df=candles, symbol="BTCUSDT", interval="1h", warmup_bars=200, predictive_mode=True)
    assert report is not None
    assert report.symbol == "BTCUSDT"


    # Find the signals generated by BacktestRunner
    # BacktestRunner signals are generated from index 200 to 224 (total 25 signals)
    # We can inspect runner.engine run inputs, but let's compare step by step
    # We rebuild the signals evaluated in BacktestRunner
    bt_signals = []
    # Extract the internal signals evaluated in BacktestRunner
    indicators = runner.indicators
    enriched_df = indicators.calculate_all(candles.copy())

    for t_idx in range(200, len(enriched_df)):
        sub_df = enriched_df.iloc[: t_idx + 1].copy()
        profile = runner.volume_profile.calculate(sub_df)
        analysis = runner.market_engine.analyze(sub_df, profile)
        signal = runner.signal_engine.evaluate(analysis, profile)
        risk = runner.risk_engine.evaluate(analysis, profile)
        intel = runner.intelligence.evaluate(analysis)
        score = runner.quant_score.calculate(analysis, signal, risk)
        regime_res = runner.regime_classifier.classify(sub_df)
        pred_res = runner.predictive_engine.evaluate(sub_df, current_regime_res=regime_res)
        decision = runner.decision_engine.evaluate(
            signal=signal,
            risk=risk,
            intelligence=intel,
            predictive=pred_res,
            regime=regime_res.regime,
            technical_score=score["score"],
            predictive_mode=True,
        )
        last_b = sub_df.iloc[-1]
        bt_signals.append({
            "timestamp": last_b["timestamp"],
            "price": float(last_b["close"]),
            "decision": decision.decision,
            "direction": decision.direction,
            "confidence": float(decision.confidence),
            "quant_score": float(score["score"]),
            "regime": regime_res.regime.value,
        })

    # 3. Run Live Replay Mode
    aggregator = CandleAggregator(symbol="BTCUSDT", interval="1h", max_bars=300)
    live_engine = LiveExecutionEngine(
        symbol="BTCUSDT",
        interval="1h",
        predictive_mode=True,
        warm_up_bars=200,
    )
    live_engine.attach_aggregator(aggregator)

    # Pre-seed aggregator with the first 200 bars (indices 0 to 199)
    aggregator.seed(candles.iloc[:200])

    # Replay subsequent candles (indices 200 to 224) as closed KlineEvents
    for idx in range(200, len(candles)):
        row = candles.iloc[idx]
        event = KlineEvent(
            symbol="BTCUSDT",
            interval="1h",
            start_time=pd.Timestamp(row["timestamp"]),
            close_time=pd.Timestamp(row["timestamp"]) + pd.Timedelta(hours=1),
            open=float(row["open"]),
            high=float(row["high"]),
            low=float(row["low"]),
            close=float(row["close"]),
            volume=float(row["volume"]),
            is_closed=True,
        )
        aggregator.process_kline(event)

    live_signals = live_engine.signal_history

    # 4. PARITY ASSERTIONS
    assert len(live_signals) == len(bt_signals), (
        f"Mismatch in signals count: live {len(live_signals)} vs backtest {len(bt_signals)}"
    )
    assert len(live_signals) == 25

    for i in range(len(live_signals)):
        live_s = live_signals[i]
        bt_s = bt_signals[i]

        # Exact timestamp match
        assert live_s.timestamp == bt_s["timestamp"], f"Bar {i}: timestamp mismatch"
        # Exact price match
        assert abs(live_s.price - bt_s["price"]) < 1e-6, f"Bar {i}: price mismatch"
        # Exact action / decision match
        assert live_s.action == bt_s["decision"], f"Bar {i}: action mismatch ({live_s.action} vs {bt_s['decision']})"
        # Exact direction match
        assert live_s.direction == bt_s["direction"], f"Bar {i}: direction mismatch"
        # Numerical confidence parity
        assert abs(live_s.confidence - bt_s["confidence"]) < 1e-4, f"Bar {i}: confidence mismatch"
        # Quant score parity
        assert abs(live_s.quant_score - bt_s["quant_score"]) < 1e-4, f"Bar {i}: quant_score mismatch"
        # Market regime parity
        assert live_s.regime == bt_s["regime"], f"Bar {i}: regime mismatch"


@patch("requests.post")
def test_end_to_end_streaming_and_notification_pipeline(mock_post, make_synthetic_candles):
    """End-to-End pipeline integration test:

    WebSocket Kline Event
            ↓
    CandleAggregator (closed bar T)
            ↓
    LiveExecutionEngine
            ↓
    SignalEvent (Single Source of Truth)
            ↓
    NotificationDispatcher (Cooldown & Filtering)
            ↓
    Discord & Telegram Channels (Mocked)
    """
    # 1. Setup Mock Responses for Discord (204) and Telegram (200)
    mock_post_calls = []

    def mock_post_handler(url, *args, **kwargs):
        resp = MagicMock()
        mock_post_calls.append({"url": url, "kwargs": kwargs})
        if "discord" in url:
            resp.status_code = 204
        elif "telegram" in url:
            resp.status_code = 200
            resp.json.return_value = {"ok": True}
        else:
            resp.status_code = 200
        return resp

    mock_post.side_effect = mock_post_handler

    # 2. Setup Dispatcher with Discord and Telegram channels
    discord_ch = DiscordWebhookChannel(
        webhook_url="https://discord.com/api/webhooks/test-hook",
        dry_run=False,
        base_backoff_sec=0.001,
    )
    telegram_ch = TelegramChannel(
        bot_token="test_token_123",
        chat_id="test_chat_999",
        dry_run=False,
        base_backoff_sec=0.001,
    )
    dispatcher = NotificationDispatcher(
        channels=[discord_ch, telegram_ch],
        min_predictive_score=0.10,  # Low threshold to ensure test delivery
        min_confidence=0.10,
        ignore_actions=set(),  # Deliver BUY, SELL, or WAIT
        cooldown_seconds=120.0,
    )

    # 3. Setup Aggregator & Live Execution Engine
    aggregator = CandleAggregator(symbol="BTCUSDT", interval="1h", max_bars=300)
    engine = LiveExecutionEngine(
        symbol="BTCUSDT",
        interval="1h",
        dispatcher=dispatcher,
        predictive_mode=True,
        warm_up_bars=200,
    )
    engine.attach_aggregator(aggregator)

    # Seed with 210 historical bars
    historical_candles = make_synthetic_candles(start="2025-01-01", periods=210, freq="1h", base_price=50000.0)
    aggregator.seed(historical_candles)

    # 4. Setup WebSocket Client
    ws_client = BinanceWebSocketClient(symbol="BTCUSDT", interval="1h", dry_run=True)
    ws_client.connect()

    # Route incoming kline messages from WebSocket into CandleAggregator
    def on_ws_kline(raw_payload: dict):
        event = KlineEvent.from_binance_payload(raw_payload)
        aggregator.process_kline(event)

    ws_client.on_kline(on_ws_kline)

    # -------------------------------------------------------------------------
    # Scenario A: Intra-bar tick (is_closed = False)
    # -------------------------------------------------------------------------
    t_open = int(pd.Timestamp("2025-01-10 00:00:00", tz="UTC").timestamp() * 1000)
    intra_msg = {
        "e": "kline",
        "s": "BTCUSDT",
        "k": {
            "t": t_open,
            "T": t_open + 3599999,
            "s": "BTCUSDT",
            "i": "1h",
            "o": "55000.0",
            "c": "55100.0",
            "h": "55200.0",
            "l": "54950.0",
            "v": "30.0",
            "x": False,  # Candle still forming!
        },
    }
    ws_client.simulate_message(intra_msg)

    # Verification: zero signals, zero notifications dispatched
    assert len(engine.signal_history) == 0
    assert len(mock_post_calls) == 0

    # -------------------------------------------------------------------------
    # Scenario B: Candle Close (is_closed = True)
    # -------------------------------------------------------------------------
    close_msg = {
        "e": "kline",
        "s": "BTCUSDT",
        "k": {
            "t": t_open,
            "T": t_open + 3599999,
            "s": "BTCUSDT",
            "i": "1h",
            "o": "55000.0",
            "c": "55300.0",
            "h": "55400.0",
            "l": "54950.0",
            "v": "150.0",
            "x": True,  # Candle T is closed!
        },
    }
    ws_client.simulate_message(close_msg)

    # Verification: 1 SignalEvent emitted
    assert len(engine.signal_history) == 1
    last_sig = engine.last_signal
    assert last_sig is not None
    assert last_sig.symbol == "BTCUSDT"
    assert last_sig.price == 55300.0

    # Verification: 2 HTTP calls dispatched (1 Discord, 1 Telegram)
    assert len(mock_post_calls) == 2
    urls = [c["url"] for c in mock_post_calls]
    assert any("discord" in u for u in urls)
    assert any("telegram" in u for u in urls)

    # Verify Discord payload structure
    discord_call = next(c for c in mock_post_calls if "discord" in c["url"])
    discord_json = discord_call["kwargs"]["json"]
    assert "embeds" in discord_json
    assert len(discord_json["embeds"]) == 1
    assert "BTCUSDT" in discord_json["embeds"][0]["title"]

    # Verify Telegram payload structure
    telegram_call = next(c for c in mock_post_calls if "telegram" in c["url"])
    telegram_json = telegram_call["kwargs"]["json"]
    assert telegram_json["chat_id"] == "test_chat_999"
    assert "BTCUSDT" in telegram_json["text"]
    assert telegram_json["parse_mode"] == "HTML"

    # -------------------------------------------------------------------------
    # Scenario C: Immediate Duplicate Close within Cooldown Window
    # -------------------------------------------------------------------------
    mock_post_calls.clear()
    ws_client.simulate_message(close_msg)

    # A second signal is recorded in the engine history
    assert len(engine.signal_history) == 2
    # BUT external dispatch is suppressed by CooldownManager!
    assert len(mock_post_calls) == 0

    # Clean shutdown
    ws_client.disconnect()
