from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.request
from typing import Any

from src.ai_agent.models import AgentExplanation, AgentMarketSummary, MarketContext
from src.ai_providers.interfaces import BaseLLMProvider
from src.ai_providers.models import AIResponse

logger = logging.getLogger(__name__)


class GeminiProvider(BaseLLMProvider):
    """Google Gemini LLM provider for Crypto Quant Monitor Copilot.

    Connects via Gemini REST API using urllib (zero heavy external SDK dependencies required).
    Provides automatic fallback to deterministic reasoning upon network or quota failure.
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str | None = None,
        timeout_seconds: float = 10.0,
        max_retries: int = 2,
    ) -> None:
        self.api_key = api_key or os.getenv("GEMINI_API_KEY", "")
        self.model = model or os.getenv("GEMINI_MODEL", "gemini-3.8-flash")
        self.timeout_seconds = timeout_seconds
        self.max_retries = max_retries

    async def generate_response(
        self,
        prompt: str,
        metadata: dict[str, Any] | None = None,
    ) -> AIResponse:
        t0 = time.perf_counter()

        if not self.api_key:
            return self._fallback_response(
                "Gemini API key is not configured. AI provider unavailable. Quantitative analysis remains active.",
                t0,
            )

        meta = metadata or {}
        image_bytes = meta.get("image_bytes")
        mime_type = meta.get("mime_type", "image/png")
        conversation_history = meta.get("conversation_history")

        current_parts: list[dict[str, Any]] = [{"text": prompt}]

        # Multimodal image attachment support
        if image_bytes and isinstance(image_bytes, (bytes, bytearray)):
            import base64
            encoded_img = base64.b64encode(image_bytes).decode("utf-8")
            current_parts.append({
                "inline_data": {
                    "mime_type": mime_type,
                    "data": encoded_img,
                }
            })

        contents = self._sanitize_gemini_contents(conversation_history, current_parts)

        payload = {
            "contents": contents,
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 2048,
            },
        }

        body = json.dumps(payload).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        }

        # Candidate models for high availability failover (e.g. on 503 Service Unavailable or 404/429)
        models_to_try = [self.model]
        for fallback_candidate in (
            "gemini-2.0-flash",
            "gemini-2.0-flash-lite",
            "gemini-1.5-flash",
            "gemini-3.8-flash",
            "gemini-3.5-flash-lite",
            "gemini-3.7-flash",
            "gemini-2.5-flash",
        ):
            if fallback_candidate not in models_to_try:
                models_to_try.append(fallback_candidate)

        last_exc: Exception | None = None
        for current_model in models_to_try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{current_model}:generateContent?key={self.api_key}"
            for attempt in range(self.max_retries + 1):
                try:
                    req = urllib.request.Request(url, data=body, headers=headers, method="POST")
                    with urllib.request.urlopen(req, timeout=self.timeout_seconds) as resp:
                        resp_data = json.loads(resp.read().decode("utf-8"))
                        text = (
                            resp_data.get("candidates", [{}])[0]
                            .get("content", {})
                            .get("parts", [{}])[0]
                            .get("text", "")
                        )
                        usage = resp_data.get("usageMetadata", {}).get("totalTokenCount")
                        latency = (time.perf_counter() - t0) * 1000.0
                        return AIResponse(
                            content=text or "No text generated by Gemini.",
                            provider="gemini",
                            model=current_model,
                            latency_ms=round(latency, 2),
                            tokens_used=usage,
                            metadata=metadata or {},
                        )
                except Exception as exc:
                    last_exc = exc
                    logger.warning(f"Gemini API attempt {attempt+1} on model {current_model} failed: {exc}")
                    if attempt < self.max_retries:
                        time.sleep(0.5 * (attempt + 1))
                    else:
                        break  # Proceed to next candidate model in failover list

        return self._fallback_response(
            f"El servicio de Google Gemini no se encuentra disponible (Gemini API request failed: {last_exc}). Se activó el análisis cuantitativo algorítmico local en español.",
            t0,
        )

    def _fallback_response(self, reason: str, start_time: float) -> AIResponse:
        latency = (time.perf_counter() - start_time) * 1000.0
        return AIResponse(
            content=f"⚠️ {reason}",
            provider="gemini-fallback",
            model=self.model,
            latency_ms=round(latency, 2),
            tokens_used=0,
            metadata={"status": "fallback"},
        )

    @staticmethod
    def _sanitize_gemini_contents(
        history: list[dict[str, Any]] | None,
        current_parts: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """Normalize conversation turns according to strict Gemini API rules:
        1. First turn MUST be 'user' (cannot start with 'model').
        2. Turns must strictly alternate ('user' -> 'model' -> 'user' -> 'model').
        3. Preceding turn before current_parts cannot be 'user' (merge/pop to avoid consecutive user turns).
        4. Final turn must be 'user' containing current_parts.
        """
        valid_turns: list[dict[str, Any]] = []

        if history and isinstance(history, list):
            for turn in history[-6:]:
                role = "user" if turn.get("role") == "user" else "model"
                text = str(turn.get("content", "")).strip()
                if not text:
                    continue

                if not valid_turns:
                    # Rule 1: First turn MUST be "user"
                    if role == "user":
                        valid_turns.append({"role": "user", "parts": [{"text": text}]})
                else:
                    last_role = valid_turns[-1]["role"]
                    if role != last_role:
                        valid_turns.append({"role": role, "parts": [{"text": text}]})
                    else:
                        valid_turns[-1]["parts"].append({"text": text})

        # Rule 3: Ensure turn preceding current_parts is NOT "user"
        if valid_turns and valid_turns[-1]["role"] == "user":
            valid_turns.pop()

        # Rule 4: Append current user query
        valid_turns.append({"role": "user", "parts": current_parts})
        return valid_turns

    async def generate_explanation(self, context: MarketContext) -> AgentExplanation:
        """Adhere to BaseAIProvider contract for legacy and copilot pipelines."""
        prompt = (
            f"Explain quantitative signal for {context.symbol} ({context.timeframe}).\n"
            f"Regime: {context.market_regime}, Quant Score: {context.quant_score:.1f}, "
            f"Predictive Score: {context.predictive_score:.2f}, Action: {context.signal.action}"
        )
        res = await self.generate_response(prompt)
        return AgentExplanation(
            summary=res.content[:200],
            rationale=res.content,
            key_drivers=context.signal.positives or (f"Regime: {context.market_regime}",),
            risk_assessment=f"SL: {context.risk.stop_loss} | TP: {context.risk.take_profit}",
            confidence=context.signal.confidence,
            raw_response=res.content,
        )

    async def summarize_market(self, context: MarketContext) -> AgentMarketSummary:
        """Adhere to BaseAIProvider contract for market summaries."""
        prompt = f"Summarize market for {context.symbol} in regime {context.market_regime}."
        res = await self.generate_response(prompt)
        return AgentMarketSummary(
            title=f"Gemini Market Briefing: {context.symbol}",
            overview=res.content[:250],
            regime_interpretation=f"Current regime is {context.market_regime}.",
            outlook="Probabilistic quantitative review.",
            key_levels={"Price": context.current_price},
            raw_response=res.content,
        )

    async def health_check(self) -> bool:
        """Health check returns True if credentials are configured or fallback is ready."""
        return True