from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.request
from typing import Any

from src.ai_agent.models import AgentExplanation, AgentMarketSummary, MarketContext
from src.ai_providers.interfaces import BaseLLMProvider
from src.ai_providers.models import AIResponse

logger = logging.getLogger(__name__)


class OpenAIProvider(BaseLLMProvider):
    """OpenAI API provider for Crypto Quant Monitor Copilot.

    Supports models like gpt-4o, gpt-4o-mini, gpt-4-turbo with zero extra dependencies.
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str | None = None,
        timeout_seconds: float = 10.0,
        max_retries: int = 2,
    ) -> None:
        self.api_key = api_key or os.getenv("OPENAI_API_KEY", "")
        self.model = model or os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self.timeout_seconds = timeout_seconds
        self.max_retries = max_retries

    async def generate_response(
        self,
        prompt: str,
        metadata: dict[str, Any] | None = None,
    ) -> AIResponse:
        t0 = time.perf_counter()

        if not self.api_key:
            return self._fallback_response(
                "OpenAI API key is not configured. Falling back to deterministic copilot interpretation.",
                t0,
            )

        url = "https://api.openai.com/v1/chat/completions"
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": "You are a quantitative market interpretation assistant."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
            "max_tokens": 1024,
        }

        body = json.dumps(payload).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }

        for attempt in range(self.max_retries + 1):
            try:
                req = urllib.request.Request(url, data=body, headers=headers, method="POST")
                with urllib.request.urlopen(req, timeout=self.timeout_seconds) as resp:
                    resp_data = json.loads(resp.read().decode("utf-8"))
                    text = (
                        resp_data.get("choices", [{}])[0]
                        .get("message", {})
                        .get("content", "")
                    )
                    usage = resp_data.get("usage", {}).get("total_tokens")
                    latency = (time.perf_counter() - t0) * 1000.0
                    return AIResponse(
                        content=text or "No text generated by OpenAI.",
                        provider="openai",
                        model=self.model,
                        latency_ms=round(latency, 2),
                        tokens_used=usage,
                        metadata=metadata or {},
                    )
            except Exception as exc:
                logger.warning(f"OpenAI API attempt {attempt+1} failed: {exc}")
                if attempt < self.max_retries:
                    time.sleep(0.5 * (attempt + 1))
                else:
                    return self._fallback_response(
                        f"OpenAI API request failed ({exc}). Quantitative context remains intact.",
                        t0,
                    )


    def _fallback_response(self, reason: str, start_time: float) -> AIResponse:
        latency = (time.perf_counter() - start_time) * 1000.0
        return AIResponse(
            content=f"⚠️ {reason}",
            provider="openai-fallback",
            model=self.model,
            latency_ms=round(latency, 2),
            tokens_used=0,
            metadata={"status": "fallback"},
        )

    async def generate_explanation(self, context: MarketContext) -> AgentExplanation:
        prompt = (
            f"Explain quantitative signal for {context.symbol} ({context.timeframe}).\n"
            f"Regime: {context.market_regime}, Quant Score: {context.quant_score:.1f}, "
            f"Predictive Score: {context.predictive_score:.2f}, Action: {context.signal.action}"
        )
        res = await self.generate_response(prompt)
        return AgentExplanation(
            summary=res.content[:200],
            rationale=res.content,
            key_drivers=context.signal.positives or (f"Regime: {context.market_regime}",),
            risk_assessment=f"SL: {context.risk.stop_loss} | TP: {context.risk.take_profit}",
            confidence=context.signal.confidence,
            raw_response=res.content,
        )

    async def summarize_market(self, context: MarketContext) -> AgentMarketSummary:
        prompt = f"Summarize market for {context.symbol} in regime {context.market_regime}."
        res = await self.generate_response(prompt)
        return AgentMarketSummary(
            title=f"OpenAI Market Briefing: {context.symbol}",
            overview=res.content[:250],
            regime_interpretation=f"Current regime is {context.market_regime}.",
            outlook="Probabilistic quantitative review.",
            key_levels={"Price": context.current_price},
            raw_response=res.content,
        )

    async def health_check(self) -> bool:
        return True