from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class AIResponse:
    """Immutable data model representing a response produced by an external or local LLM provider.

    STRICT CONSTRAINTS:
    - Purely narrative/interpretive decision-support output.
    - Zero execution authority (no trades, orders, or quantitative score alteration).
    """

    content: str
    provider: str
    model: str
    latency_ms: float
    tokens_used: int | None = None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)
    disclaimer: str = (
        "DECISION SUPPORT ONLY: Generated by AI Provider for human operator interpretation. "
        "Crypto Quant Monitor provides quantitative analysis, not automated trade execution."
    )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)