from __future__ import annotations

import inspect
import logging
from typing import Any, Callable

from src.ai_agent.context_builder import ContextBuilder
from src.ai_agent.models import MarketContext
from src.notifications.models import SignalEvent
from src.operator_service.interfaces import BaseMarketContextProvider

logger = logging.getLogger(__name__)


class LiveAIContextBridge:
    """Lightweight integration bridge connecting real-time signal events to the AI Operator layer.

    Adheres strictly to the architectural constraints:
    - SignalEvent remains the single source of truth.
    - Zero look-ahead bias (evaluates only closed candle T events).
    - Never recalculates indicators, predictions, or quantitative scores.
    - Updates are non-blocking and fault-isolated.
    """

    def __init__(
        self,
        context_provider: BaseMarketContextProvider,
        context_builder: type[ContextBuilder] = ContextBuilder,
    ) -> None:
        """Initialize the live bridge.

        Args:
            context_provider: Target context repository to update (e.g. InMemoryMarketContextProvider).
            context_builder: Builder class responsible for transforming SignalEvent to MarketContext.
        """
        self._context_provider = context_provider
        self._context_builder = context_builder
        self._subscribers: list[Callable[[MarketContext], Any]] = []
        self._processed_count: int = 0
        self._last_context: MarketContext | None = None

    @property
    def context_provider(self) -> BaseMarketContextProvider:
        """Reference to the underlying context provider."""
        return self._context_provider

    @property
    def processed_count(self) -> int:
        """Total number of SignalEvents converted and bridged."""
        return self._processed_count

    @property
    def last_context(self) -> MarketContext | None:
        """Most recent MarketContext generated by this bridge."""
        return self._last_context

    def subscribe(self, callback: Callable[[MarketContext], Any]) -> None:
        """Register a downstream listener to be notified when a new MarketContext is created."""
        self._subscribers.append(callback)

    def attach_to_live_engine(self, engine: Any) -> None:
        """Attach this bridge directly to a LiveExecutionEngine instance.

        Registers `on_signal_event` into the engine's `on_signal` listener list.
        """
        if hasattr(engine, "on_signal") and callable(engine.on_signal):
            engine.on_signal(self.on_signal_event)
            logger.info(f"LiveAIContextBridge successfully attached to engine {engine}")
        else:
            raise TypeError(f"Target engine {engine} does not support .on_signal() registration.")

    def on_signal_event(
        self,
        signal_event: SignalEvent,
        market_report: dict[str, Any] | None = None,
        extra_metadata: dict[str, Any] | None = None,
    ) -> MarketContext:
        """Synchronous handler invoked upon arrival of a newly closed candle SignalEvent.

        Converts the SignalEvent into a MarketContext snapshot and updates the context provider.
        """
        context = self._context_builder.build_from_signal_event(
            signal_event=signal_event,
            market_report=market_report,
            extra_metadata=extra_metadata,
        )

        # Update target context provider
        if hasattr(self._context_provider, "update_context") and callable(
            self._context_provider.update_context
        ):
            self._context_provider.update_context(context)

        self._last_context = context
        self._processed_count += 1

        # Notify downstream subscribers with exception isolation
        for sub in self._subscribers:
            try:
                res = sub(context)
                if inspect.isawaitable(res):
                    logger.debug("Async subscriber detected in sync context; closing unawaited coroutine.")
                    if inspect.iscoroutine(res):
                        res.close()
            except Exception as exc:
                logger.error(f"Error in LiveAIContextBridge subscriber {sub}: {exc}", exc_info=True)


        return context

    async def on_signal_event_async(
        self,
        signal_event: SignalEvent,
        market_report: dict[str, Any] | None = None,
        extra_metadata: dict[str, Any] | None = None,
    ) -> MarketContext:
        """Asynchronous non-blocking handler for event-loop environments."""
        context = self._context_builder.build_from_signal_event(
            signal_event=signal_event,
            market_report=market_report,
            extra_metadata=extra_metadata,
        )

        if hasattr(self._context_provider, "update_context") and callable(
            self._context_provider.update_context
        ):
            self._context_provider.update_context(context)

        self._last_context = context
        self._processed_count += 1

        for sub in self._subscribers:
            try:
                res = sub(context)
                if inspect.isawaitable(res):
                    await res
            except Exception as exc:
                logger.error(f"Error in LiveAIContextBridge async subscriber {sub}: {exc}", exc_info=True)

        return context
